Feature/authorization
maurosaravia/rs-blackmarket pull request #10
Opened 2022-08-09 18:12 UTC by maurosaravia

## Pull request type

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

- Users can sign in, currently the system provides a token but doesn't check it if provided.

## What is the new behavior?

- Authorization is added to the system.
- Some methods can be accessed by everyone (e.g: sign in)
- Some methods can be accessed by signed in users (e.g: list categories)
- Some methods can be accessed by signed in users with specific roles (e.g: admins can delete categories)

## Other information

## Preview

N/A

2022-08-09 18:51 UTC, slasia requested changes

2022-08-09 18:51 UTC, slasia commented on src/auth/auth.module.ts
> +        secret: process.env.JWT_SECRET,
Just a recomendation, you can use [schema-validation](https://docs.nestjs.com/techniques/configuration#schema-validation) in app.module.ts, to validate env vars.  Its a good practice  to check that some variables are present and are of the expected type. For example: 




`      validationSchema: Joi.object({
              JWT_SECRET:Joi.string().required()
      }),`

2022-08-09 18:51 UTC, slasia commented on src/auth/guards/roles.guard.ts
> +import { ROLES_KEY } from '../decorators/roles.decorator';
I think you can use the path alias, what do you think?

2022-08-09 18:51 UTC, slasia commented on src/auth/guards/jwt.strategy.ts
> +  async validate(payload: any) {
Please avoid **any**, its important to define the type of each attributes

2022-08-09 19:40 UTC, maurosaravia commented on src/auth/guards/jwt.strategy.ts
> +    return { userId: payload.data.userId, role: payload.data.role };
The payload will always have those properties because it was issued by the system.
Also I noticed that it is unneccessary to construct the object, returning payload.data should be enough

2022-08-09 19:40 UTC, maurosaravia commented on src/auth/guards/roles.guard.ts
> +    ]);
I think you are right, the context.getClass seems to be unneccessary

2022-08-09 19:41 UTC, maurosaravia commented on src/categories/controllers/categories.controller.ts
>  @Controller('categories')
I think I should do that with the JwtGuard, because it is on every endpoint. I can't do the same with the RolesGuard.

2022-08-09 19:42 UTC, maurosaravia commented on src/users/services/users.service.ts
> +    });
I agree. I already have a custom repository, this logic is misplaced

2022-08-09 19:50 UTC, maurosaravia commented on src/auth/guards/roles.guard.ts
> +    ]);
> I think you are right, the context.getClass seems to be unneccessary

I was wrong, context.getClass is neccessary to be able to use the Guard at the controller level.

2022-08-16 12:29 UTC, maurosaravia commented on src/users/services/users.service.ts
> +    return this.usersRepo.findByEmail(email);
You are right, the validation is missing

2022-08-16 13:06 UTC, maurosaravia commented on src/users/services/users.service.ts
> +    const category = this.usersRepo.findByEmail(email);
It seems that I forgot to save the file with the await before commiting

2022-08-22 13:38 UTC, merged