Feature/products
maurosaravia/rs-blackmarket pull request #11
Opened 2022-08-22 13:53 UTC by maurosaravia

## Pull request type

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

## What is the new behavior?

- Products and status added to the system.
- Status can be 'used', 'new' or 'other'.
- Products have a name, description, price, rating, status, stock and a list of categories.
- Products can be created by an admin.

https://trello.com/c/dHzFTe1H
## Other information

## Preview

N/A

2022-08-22 14:48 UTC, EMazzaglia requested changes
Buen trabajo, te deje algunas preguntas. Sorry por el review en español pero me parece que va a ser un poco mas rico para ambos.

2022-08-22 14:48 UTC, EMazzaglia commented on src/products/entities/product.entity.ts
> +  name!: string;
creo que los ! no son necesarios, los productos van a ser creados una vez que la entidad es "valida", entonces me parece redundante usarlos. A vos que te parece?

2022-08-22 14:48 UTC, EMazzaglia commented on src/products/services/products.service.ts
> +    return this.productsRepo.saveDTO(createProductDto);
Ojo aca, no deberias nunca persistir un DTO directamente, tiene que primero pasarse a una entidad, para que se mapee correctamente a la DB.

2022-08-22 14:48 UTC, EMazzaglia commented on src/users/services/users.service.ts
> +    const password = this.hashPassword(createUserDto.password);
Bien con esto, ojo con meter 200 cosas en un PR. Acordate, mientras mas unitario sea el PR, mejor para corregir, rollbackear, entender qeu se hizo, etc etc.

2022-08-22 14:48 UTC, EMazzaglia commented on test/products.e2e-spec.ts
> +        .set('Authorization', 'Bearer ' + accessToken)
fijate que aca la parte de seteo del token lo estas harcodeando por todos lados :) Podriamos mejorarlo no? Acordate de DRY (Do not repeat yourself)

2022-08-22 15:15 UTC, maurosaravia commented on test/products.e2e-spec.ts
> +        .set('Authorization', 'Bearer ' + accessToken)
La función set solo puede ser utilizada mientras se está creando la request. Voy a buscar si existe otra forma de agregar un header en la que no sea necesario repetir el paso, o tal vez haciendo un mock de la guard para que el auth no sea necesario

2022-08-22 15:16 UTC, maurosaravia commented on src/products/services/products.service.ts
> +    return this.productsRepo.saveDTO(createProductDto);
No se esta persistiendo directamente el DTO, dentro de la función se transforma a la entidad Product y se guarda eso en la DB

2022-08-22 15:20 UTC, maurosaravia commented on src/products/entities/product.entity.ts
> +  name!: string;
Los "!" son redundantes sí. Los incluí porque las validaciones se realizan en ProductDTO y preferí que en Product también se pueda visualizar el requerimiento.

2022-08-25 13:36 UTC, EMazzaglia commented on src/products/entities/product.entity.ts
> +  name!: string;
No es necesario, con las annotations de class validator ya nos aseguramos que esos campos tengan datos.

2022-08-29 14:13 UTC, maurosaravia commented on src/database/migrations/1660766828733-products.ts
> +    public async up(queryRunner: QueryRunner): Promise<void> {
The migration is autogenerated this way by typeorm. Also the query runner is an argument in the up and down functions, I think running the migrations only uses one query runner

2022-08-29 14:13 UTC, maurosaravia commented on src/products/controllers/products.controller.spec.ts
> +    });
I think the toEqual already accounts for that, if it's not defined or it's not a product the toEqual will fail

2022-08-29 19:43 UTC, merged