Categories added to the system
maurosaravia/rs-blackmarket pull request #3
Opened 2022-06-10 15:54 UTC by maurosaravia

## Pull request type

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

## What is the new behavior?

- Categories added to the system
- Categories can have a name, a parent category and a list of children categories
- Categories can be read

https://trello.com/c/Ed3nFyIG
https://trello.com/c/zNQhh19d

## Other information

## Preview

N/A

2022-06-10 17:02 UTC, Alxzu approved these changes
Looks good! Well organized + tested + super helpful description 😄 👍

2022-06-10 17:23 UTC, ernes128 requested changes
Hey buddy, awesome job. I suggested you some changes. Take a look at them and after implementing we could review your tests. Let me know if I can help you with anything else

2022-06-10 17:23 UTC, ernes128 commented on src/categories/controllers/categories.controller.ts
> +  getall() {
I think you could make this function async to avoid blocking operations. What do you think?

Also adding the return type of your functions is a good practice. It lets the reader knows easily and quickly what kind of datatype you are returning.

Example:
```typescript
async getAll(): Promise<Category[]> {
  // your function definition here
}
```

2022-06-10 17:23 UTC, ernes128 commented on src/categories/controllers/categories.controller.ts
> +  constructor(private categoriesService: CategoriesService) {}
Defining this property as readonly could be a good addition to avoid re-assignations.
```typescript
  constructor(private readonly categoriesService: CategoriesService) {}
```

2022-06-10 17:23 UTC, ernes128 commented on src/categories/controllers/categories.controller.ts
> +  async getOne(@Param('id') id: number) {
As suggested above, adding the function return type would be ideal. On the other hand, if your ID is a number, as you are sending it in the URL it will be a string by default. You can parse it as number taking advantage of the ParseIntPipe that NestJS offers out of the box. 

Example:

```typescript
async getOne(@Param('id', ParseIntPipe) id: number)
```

2022-06-10 17:23 UTC, ernes128 commented on src/categories/dtos/category.dto.ts
> +  name: string;
Is this field required? If so, I would suggest adding the @IsNotEmpty decorator. Also you can use @MinLength and @IsString to ensure the minimun lenght (if needed) and datatype

2022-06-10 17:23 UTC, ernes128 commented on src/categories/dtos/category.dto.ts
> +  parentCategoryId?: number;
Is this field required? If so, I would suggest adding the @isnotempty decorator. Also, the ID should be a positive number, right? So you can use the @IsPositive decorator too.

2022-06-10 17:23 UTC, ernes128 commented on src/categories/services/categories.service.ts
> +      return (await this.categoriesRepo.count({ id: id })) > 0;
Please do not use return await.

When you declare an async function, it automatically envelops the return of that function as a promise if it is not a promise already. 

Example: 

```javascript
async getName(): Promise<string> {
   return 'ernesto';
}
```
The example shown above does not return a string. It returns a promise that resolves in a string value. 


On the other hand, when you use await inside in an async function you are expecting that function to be executed from the micro-task queue on the Event Loop, and that's results in resolving the promised value. 

Example:

```javascript
async printer(): Promise<string> {
   const name: string = await getName(); -------> /// What you are doing here is expecting the promise to resolve so you have a plain string value and not a Promise that resolves in a string (Promise<string>)
   return name;
}
```

So what happens when you use "return await" inside an async function is basically adding additional delay because await pauses the execution until the promise is resolved (or rejected) and then, as you are doing this inside an async function you are forcing to re-promise the value (basically you have a promise, waits it to resolve, and then you are returning a promise again because that's the nature of async functions)


------

Plus, in your particular case (using try/catch) in order to properly catch the error if something happens, you should let the async function resolve properly first, and then return it. Otherwise you will return a promise directly and the catch will never get anything if some error happens as its out of its context

Example:

```typescript
try{
const categoriesCount = await this.categoriesRepo.count({ id: id }); // If something fails here, will be catch in the "Catch" clause
return categoriesCount > 0;
} catch(error) {
 // your error handling logic here
}
```

2022-06-10 17:23 UTC, ernes128 commented on src/categories/services/categories.service.ts
> +    @InjectRepository(Category) private categoriesRepo: Repository<Category>,
I would recommend you creating a custom repository in order to separate the database logic from the bussiness logic. 

Example

```typescript
@EntityRepository(Category)
export class CategoryRepository extends Repository<Category> {
// your custom db operations here
}
```

And also in your service 

```typescript
@InjectRepository(CategoryRepository) private categoriesRepo: CategoryRepository,
```

So now you have your database logic in your "category.repository.ts" file and the service only calls it without dealing with ORM/SQL functions.

2022-06-10 17:23 UTC, ernes128 commented on src/categories/services/categories.service.ts
> +    }
As explained before, this will never work, because if something fails the catch will be out of the promise resolution context.

2022-06-10 17:23 UTC, ernes128 commented on src/categories/services/categories.service.ts
> +  }
You can take advantage of the findOneOrFail function that TypeORM provides you. 

Example in your category.repository.ts

```typescript
export function findById(id: number): Promise<Category>{
return this.findOneOrFail(id);
}
```

And then in your category.service.ts

```typescript
try{
const category = await this.categoryRepository.findById(id);
return category;
} catch (error) {
 throw new CategoryNotFoundException();
}
```

2022-06-10 17:23 UTC, ernes128 commented on src/database/migrations/1654870950343-categories.ts
> +        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varyin
I would recommend adding also a "deleted_at" column to handle logic deletions.

2022-06-10 17:43 UTC, slasia requested changes
Good work Mauro! I Just add some comments that may help you. Look at them and tell me what you think, I am at your disposal

2022-06-10 17:43 UTC, slasia commented on src/categories/controllers/categories.controller.spec.ts
> +  mockCategory.name = 'test';
- In order to use a differents values in your mock objects you can use [faker](https://www.npmjs.com/package/faker/v/5.5.3), with that value you can test with real values. 
- You can write all the mocks in a separate file, for example: /mocks/categories.mock.ts , to have the information modularized and in the future you will be able to reuse the information of the mocks. Are you agree?

2022-06-10 17:43 UTC, slasia commented on src/categories/dtos/category.dto.ts
> +  @MaxLength(50)
You can add  ` @IsString()` and   `@IsNotEmpty()`
decorator, what do you think?

2022-06-10 17:43 UTC, slasia commented on src/categories/services/categories.service.spec.ts
> +  mockCategory.name = 'test';
Same comment that I wrote in controller test

2022-06-10 17:43 UTC, slasia commented on src/categories/services/categories.service.ts
> +  async exists(id: number): Promise<boolean> {
Can you add unit test to this method?

2022-06-10 17:43 UTC, slasia commented on src/categories/services/categories.service.spec.ts
> +    expect(service.findAll()).toBe(mockCategories);
Can you add unit test to get an error in services.findAll()?

2022-06-10 17:43 UTC, slasia commented on src/categories/services/categories.service.ts
> +      return (await this.categoriesRepo.count({ id: id })) > 0;
You can create another layer like: categories.repository.ts , to separate business logic to database logic. just as you separated controller from services, you can separate repository from services

2022-06-10 17:58 UTC, maurosaravia commented on src/categories/services/categories.service.spec.ts
> +  mockChildCategory.createdAt = new Date();
The repository is being mocked in this test, because of this the orm won't auto populate these 2 fields

2022-06-10 17:59 UTC, maurosaravia commented on src/categories/controllers/categories.controller.ts
> +  getall() {
I agree

2022-06-10 18:11 UTC, maurosaravia commented on src/categories/controllers/categories.controller.ts
> +  async getOne(@Param('id') id: number) {
Thanks, I didn't know about this

2022-06-10 18:13 UTC, maurosaravia commented on src/categories/dtos/category.dto.ts
> +  parentCategoryId?: number;
The parentCategoryId is not required

2022-06-10 18:27 UTC, maurosaravia commented on src/categories/services/categories.service.ts
> +      return (await this.categoriesRepo.count({ id: id })) > 0;
In this case I don't think it does a "return await", it awaits for the count result and then checks if it's greater than 0, returning a boolean. If I don't wait for the Promise<number> I can't compare it to 0.
On the other hand, I think that waiting for the count as written should result in the error being catched, because the promise is being resolved in the try/catch and the potential error will be thrown in the correct context.

2022-06-10 18:30 UTC, ernes128 commented on src/categories/dtos/category.dto.ts
> +  name: string;
If the card isn't accurate is a good practice to ask to your product owner/business analyst if this field should or not be required.

2022-06-16 18:50 UTC, slasia approved these changes
Good work! 
It would be good if you separate the mocks into different files, this way you can reuse them and the test files are cleaner

2022-06-16 18:50 UTC, slasia commented on src/categories/services/categories.service.ts
> +      const category = await this.categoriesRepo.findById(id);
Can you use `findOneOrFail` ?

2022-06-16 20:34 UTC, maurosaravia commented on src/categories/services/categories.service.ts
> +      const category = await this.categoriesRepo.findById(id);
findById is defined by me, it uses findOneOrFail. You can see it in the categories.repository.ts file.

2022-06-17 19:52 UTC, merged