Feature/create user
maurosaravia/rs-blackmarket pull request #7
Opened 2022-07-21 19:31 UTC by maurosaravia

## Pull request type

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

- Users exist in the system

## What is the new behavior?

- Users can be created
- The system has clear error messages in case of an incorrect use

## Other information

## Preview

N/A

2022-07-22 14:15 UTC, EMazzaglia requested changes
Code seems ok, there are few changes requested. Good job!

2022-07-22 14:15 UTC, EMazzaglia commented on src/users/dtos/user.dto.ts
> +  @Matches(/((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/, {
This is ok, but the Regex should be extracted as a constant here. So we don't fall into a DRY violation

2022-07-22 14:15 UTC, EMazzaglia commented on src/users/dtos/user.dto.ts
> +  constructor(user?: IUser) {
user should not be an optional parameter right?
If we are using this constructor user might be defined. Otherwise, we are allowing the user with empty fields to be created

2022-07-22 14:15 UTC, EMazzaglia commented on src/users/repositories/users.repository.ts
> +  createUser(createUserDto: UserDTO): Promise<User> {
usually if you are working inside of a `UsersRepository` methods can be written without the User word inside. 
so instead of `createUser` you can just define `create`

2022-07-26 16:55 UTC, EMazzaglia commented
Any news from this PR?

2022-07-27 16:53 UTC, Alxzu approved these changes

2022-07-28 16:26 UTC, merged