Feature/signin
maurosaravia/rs-blackmarket pull request #9
Opened 2022-08-01 13:11 UTC by maurosaravia

## Pull request type

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

- Users can register in the system but can't sign in

## What is the new behavior?

- Users can sign in to the system using its email and password

https://trello.com/c/AJ9pHD69
## Other information

## Preview

N/A

2022-08-02 16:27 UTC, EMazzaglia requested changes
Hello good job so far, I left some comments. 
Also, It would be nice if you could add some e2e tests for this feature.
Let me know when changes are applied :)

2022-08-02 16:27 UTC, EMazzaglia commented on src/auth/auth.module.ts
> +    PassportModule.register({ defaultStrategy: 'jwt' }),
Hello, make use of a constant to set the value for the `defaultStrategy` to avoid falling into DRY violation. Ty!

2022-08-02 16:27 UTC, EMazzaglia commented on src/auth/controllers/auth.controller.ts
> +  async signin(@Body() signInDto: SignInDTO): Promise<{ accessToken }> {
Be careful with using an object as return type for a function. This is propense to cause repetitions of code but even more important, is an object that have no identity. 
To improve this, it's recommended to create your[ own types or interfaces](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html). 

```typescript
Promise<{ accessToken }>
```

2022-08-02 16:27 UTC, EMazzaglia commented on src/auth/dtos/signin.dto.ts
> +  constructor(signin: ISignin) {
```suggestion
  constructor(signin: ISignIn) {
```

2022-08-02 16:27 UTC, EMazzaglia commented on src/auth/dtos/signin.dto.ts
> +  password: string;
You could improve this using a regex. Maybe on later PRs could be applied.

2022-08-02 16:27 UTC, EMazzaglia commented on src/auth/interfaces/signin.interface.ts
> +export interface ISignin {
```suggestion
export interface ISignIn {
```

2022-08-02 16:27 UTC, EMazzaglia commented on src/auth/interfaces/signup.interface.ts
> +export interface ISignup extends ISignin {
```suggestion
export interface ISignUp extends ISignIn {
```

2022-08-10 13:45 UTC, EMazzaglia requested changes
Left some small changes to be addressed and also a few questions. But it's looking way better.

2022-08-10 13:45 UTC, EMazzaglia commented on src/auth/auth.module.ts
> +    PassportModule.register({ defaultStrategy: DEFAULT_STRATEGY }),
```suggestion
    PassportModule.register({ defaultStrategy: JWT_STRATEGY }),
```

2022-08-10 13:45 UTC, EMazzaglia commented on src/auth/dtos/signup.dto.ts
> +  constructor(user?: ISignUp) {
Is it makes sense to have this property as optional? I mean if i want to create a `SignUpDTO` the field should be mandatory maybe?

2022-08-10 13:45 UTC, EMazzaglia commented on test/auth.e2e-spec.ts
> +      const response = await request(app.getHttpServer())
app.getHttpServer() could be extracted as a shared variable between tests.

2022-08-10 13:45 UTC, EMazzaglia commented on test/auth.e2e-spec.ts
> +    app.useGlobalPipes(new ValidationPipe());
Are these pipes not included on the testing module?

2022-08-10 13:49 UTC, maurosaravia commented on src/auth/dtos/signup.dto.ts
> +  constructor(user?: ISignUp) {
I found out that the validation pipe requires the constructor parameter as optional to work properly

2022-08-10 14:04 UTC, maurosaravia commented on test/auth.e2e-spec.ts
> +    app.useGlobalPipes(new ValidationPipe());
The pipe currently is not included in the AppModule, it is set in the main.ts file after creating the application.
This can be changed easily

2022-08-22 13:37 UTC, merged